# Auto-generated from textbook.sqlite3 – 100 Bücher

books = [
    {"id": 1, "title": 'Frankenstein', "author": 'Mary Shelley'},
    {"id": 2, "title": 'Wuthering Heights', "author": 'Emily Brontë'},
    {"id": 3, "title": 'Crime and Punishment', "author": 'Fyodor Dostoevsky'},
    {"id": 4, "title": 'Peer Gynt', "author": 'Henrik Ibsen'},
    {"id": 5, "title": 'War and Peace', "author": 'Leo Tolstoy'},
    {"id": 6, "title": 'Anna Karenina', "author": 'Leo Tolstoy'},
    {"id": 7, "title": "A Doll's House", "author": 'Henrik Ibsen'},
    {"id": 8, "title": 'The Brothers Karamazov', "author": 'Fyodor Dostoevsky'},
    {"id": 9, "title": 'Buddenbrooks', "author": 'Thomas Mann'},
    {"id": 10, "title": 'Gitanjali', "author": 'Rabindranath Tagore'},
    {"id": 11, "title": 'Death in Venice', "author": 'Thomas Mann'},
    {"id": 12, "title": 'O Pioneers!', "author": 'Willa Cather'},
    {"id": 13, "title": 'The Metamorphosis', "author": 'Franz Kafka'},
    {"id": 14, "title": 'The Song of the Lark', "author": 'Willa Cather'},
    {"id": 15, "title": 'My Antonia', "author": 'Willa Cather'},
    {"id": 16, "title": 'One of Ours', "author": 'Willa Cather'},
    {"id": 17, "title": 'The Magic Mountain', "author": 'Thomas Mann'},
    {"id": 18, "title": 'Naomi', "author": "Jun'ichirō Tanizaki"},
    {"id": 19, "title": 'Mrs Dalloway', "author": 'Virginia Woolf'},
    {"id": 20, "title": 'The Trial', "author": 'Franz Kafka'},
    {"id": 21, "title": 'To the Lighthouse', "author": 'Virginia Woolf'},
    {"id": 22, "title": 'Orlando', "author": 'Virginia Woolf'},
    {"id": 23, "title": 'The Sound and the Fury', "author": 'William Faulkner'},
    {"id": 24, "title": "A Room of One's Own", "author": 'Virginia Woolf'},
    {"id": 25, "title": 'As I Lay Dying', "author": 'William Faulkner'},
    {"id": 26, "title": 'Absalom, Absalom!', "author": 'William Faulkner'},
    {"id": 27, "title": 'Of Mice and Men', "author": 'John Steinbeck'},
    {"id": 28, "title": 'The Hobbit', "author": 'J.R.R. Tolkien'},
    {"id": 29, "title": 'The Grapes of Wrath', "author": 'John Steinbeck'},
    {"id": 30, "title": 'Lotte in Weimar', "author": 'Thomas Mann'},
    {"id": 31, "title": 'Native Son', "author": 'Richard Wright'},
    {"id": 32, "title": 'The Stranger', "author": 'Albert Camus'},
    {"id": 33, "title": 'Cannery Row', "author": 'John Steinbeck'},
    {"id": 34, "title": 'Black Boy', "author": 'Richard Wright'},
    {"id": 35, "title": 'Doctor Faustus', "author": 'Thomas Mann'},
    {"id": 36, "title": 'The Grass is Singing', "author": 'Doris Lessing'},
    {"id": 37, "title": 'The Holy Sinner', "author": 'Thomas Mann'},
    {"id": 38, "title": 'East of Eden', "author": 'John Steinbeck'},
    {"id": 39, "title": 'Invisible Man', "author": 'Ralph Ellison'},
    {"id": 40, "title": 'The Outsider', "author": 'Richard Wright'},
    {"id": 41, "title": 'Go Tell It on the Mountain', "author": 'James Baldwin'},
    {"id": 42, "title": 'A Fable', "author": 'William Faulkner'},
    {"id": 43, "title": 'The Fellowship of the Ring', "author": 'J.R.R. Tolkien'},
    {"id": 44, "title": 'The Two Towers', "author": 'J.R.R. Tolkien'},
    {"id": 45, "title": 'The Return of the King', "author": 'J.R.R. Tolkien'},
    {"id": 46, "title": 'Notes of a Native Son', "author": 'James Baldwin'},
    {"id": 47, "title": 'Howl and Other Poems', "author": 'Allen Ginsberg'},
    {"id": 48, "title": 'The City and the Stars', "author": 'Arthur C. Clarke'},
    {"id": 49, "title": "Giovanni's Room", "author": 'James Baldwin'},
    {"id": 50, "title": 'Night', "author": 'Elie Wiesel'},
    {"id": 51, "title": 'Things Fall Apart', "author": 'Chinua Achebe'},
    {"id": 52, "title": 'No Longer at Ease', "author": 'Chinua Achebe'},
    {"id": 53, "title": 'To Kill a Mockingbird', "author": 'Harper Lee'},
    {"id": 54, "title": 'A House for Mr. Biswas', "author": 'V. S. Naipaul'},
    {"id": 55, "title": 'Nobody Knows My Name', "author": 'James Baldwin'},
    {"id": 56, "title": 'Kaddish and Other Poems', "author": 'Allen Ginsberg'},
    {"id": 57, "title": 'Another Country', "author": 'James Baldwin'},
    {"id": 58, "title": 'The Reivers', "author": 'William Faulkner'},
    {"id": 59, "title": 'The Golden Notebook', "author": 'Doris Lessing'},
    {"id": 60, "title": 'Children of the New World', "author": 'Assia Djebar'},
    {"id": 61, "title": 'The General of the Dead Army', "author": 'Ismail Kadare'},
    {"id": 62, "title": 'The Time of the Hero', "author": 'Mario Vargas Llosa'},
    {"id": 63, "title": 'Way Station', "author": 'Clifford Simak'},
    {"id": 64, "title": 'Arrow of God', "author": 'Chinua Achebe'},
    {"id": 65, "title": 'A Man of the People', "author": 'Chinua Achebe'},
    {"id": 66, "title": 'One Hundred Years of Solitude', "author": 'Gabriel García Márquez'},
    {"id": 67, "title": 'Dance of the Happy Shades', "author": 'Alice Munro'},
    {"id": 68, "title": 'House Made of Dawn', "author": 'N. Scott Momaday'},
    {"id": 69, "title": 'A Wizard of Earthsea', "author": 'Ursula K. Le Guin'},
    {"id": 70, "title": '2001: A Space Odyssey', "author": 'Arthur C. Clarke'},
    {"id": 71, "title": "Tell Me How Long the Train's Been Gone", "author": 'James Baldwin'},
    {"id": 72, "title": 'When Rain Clouds Gather', "author": 'Bessie Head'},
    {"id": 73, "title": 'Conversation in the Cathedral', "author": 'Mario Vargas Llosa'},
    {"id": 74, "title": 'The Way to Rainy Mountain', "author": 'N. Scott Momaday'},
    {"id": 75, "title": 'The Left Hand of Darkness', "author": 'Ursula K. Le Guin'},
    {"id": 76, "title": 'From a Crooked Rib', "author": 'Nuruddin Farah'},
    {"id": 77, "title": 'Twenty Poems', "author": 'Tomas Tranströmer'},
    {"id": 78, "title": 'The Bluest Eye', "author": 'Toni Morrison'},
    {"id": 79, "title": 'The Tombs of Atuan', "author": 'Ursula K. Le Guin'},
    {"id": 80, "title": 'The Siege', "author": 'Ismail Kadare'},
    {"id": 81, "title": 'In a Free State', "author": 'V. S. Naipaul'},
    {"id": 82, "title": 'Chronicle in Stone', "author": 'Ismail Kadare'},
    {"id": 83, "title": 'Maru', "author": 'Bessie Head'},
    {"id": 84, "title": 'The Farthest Shore', "author": 'Ursula K. Le Guin'},
    {"id": 85, "title": 'The Fall of America', "author": 'Allen Ginsberg'},
    {"id": 86, "title": 'Rendezvous with Rama', "author": 'Arthur C. Clarke'},
    {"id": 87, "title": 'Sula', "author": 'Toni Morrison'},
    {"id": 88, "title": 'A Question of Power', "author": 'Bessie Head'},
    {"id": 89, "title": 'The Dispossessed', "author": 'Ursula K. Le Guin'},
    {"id": 90, "title": 'Baltics', "author": 'Tomas Tranströmer'},
    {"id": 91, "title": 'If Beale Street Could Talk', "author": 'James Baldwin'},
    {"id": 92, "title": 'Johnno', "author": 'David Malouf'},
    {"id": 93, "title": 'Who Do You Think You Are?', "author": 'Alice Munro'},
    {"id": 94, "title": 'Song of Solomon', "author": 'Toni Morrison'},
    {"id": 95, "title": 'The Sea, the Sea', "author": 'Iris Murdoch'},
    {"id": 96, "title": 'The Fountains of Paradise', "author": 'Arthur C. Clarke'},
    {"id": 97, "title": 'A Bend in the River', "author": 'V. S. Naipaul'},
    {"id": 98, "title": 'Just Above My Head', "author": 'James Baldwin'},
    {"id": 99, "title": 'Downbelow Station', "author": 'C. J. Cherryh'},
    {"id": 100, "title": 'Storyteller', "author": 'Leslie Marmon Silko'},
]
